using BlazorWebAppMovies.Components;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using BlazorWebAppMovies.Data;
using Telekinesis.Medium;
using Telekinesis.Medium.Blazor;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddDbContextFactory<BlazorWebAppMoviesContext>(options =>
    options.UseSqlite(builder.Configuration.GetConnectionString("BlazorWebAppMoviesContext")
        ?? throw new InvalidOperationException("Connection string 'BlazorWebAppMoviesContext' not found.")));

builder.Services.AddQuickGridEntityFrameworkAdapter();

builder.Services.AddDatabaseDeveloperPageExceptionFilter();

// Add services to the container.
builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents();
builder.Services.AddTelekinesisMedium();

var app = builder.Build();

using (var scope = app.Services.CreateScope())
{
    var services = scope.ServiceProvider;
    SeedData.Initialize(services);
}

// Medium: merge the semantics the Roslyn generator autogenerated from the [Medium*]-annotated
// movie commands, and persist them as the sidecar Telekinesis's MediumDiscovery reads next
// to the executable (so it can merge them onto the page's accessibility tree).
var medium = app.Services.GetRequiredService<MediumManifestBuilder>();
medium.Application = "BlazorWebAppMovies";
var generated = Telekinesis.Medium.Generated.GeneratedMedium.Build();
foreach (var element in generated.Views.Values.SelectMany(v => v.Elements).Concat(generated.Elements))
    medium.Register(element);
File.WriteAllText(
    Path.Combine(AppContext.BaseDirectory, MediumSchema.FileName),
    MediumJson.Serialize(medium.Build()));

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error", createScopeForErrors: true);
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
    app.UseMigrationsEndPoint();
}
app.UseStatusCodePagesWithReExecute("/not-found", createScopeForStatusCodePages: true);
app.UseHttpsRedirection();

app.UseAntiforgery();

app.MapStaticAssets();
app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode();
app.MapMediumManifest();

app.Run();
