using System.Text;

namespace Telekinesis.Medium;

/// <summary>
/// Rules for stable, deterministic semantic ids (issue #28).
///
/// An id is app-unique, independent of screen coordinates and transient accessibility
/// runtime ids, and should survive harmless UI refactors. Canonical form is
/// dot-separated lowercase segments: <c>invoice.customer</c>, <c>navigation.settings</c>.
///
/// <see cref="TryNormalize"/> is the deterministic fallback generator (the same input
/// always yields the same output — never random or coordinate-based). Developers can and
/// should override autogenerated ids explicitly when the business meaning matters.
/// </summary>
public static class MediumSemanticId
{
    /// <summary>
    /// Normalize a raw id to canonical dot-separated form. Returns false and sets
    /// <paramref name="error"/> when no usable characters remain.
    /// </summary>
    public static bool TryNormalize(string? raw, out string? normalized, out string? error)
    {
        normalized = null;
        error = null;

        if (string.IsNullOrWhiteSpace(raw))
        {
            error = "Semantic id is empty.";
            return false;
        }

        var s = InsertCamelBoundaries(raw).ToLowerInvariant();
        var segments = new List<string>();
        var cur = new StringBuilder();

        foreach (var ch in s)
        {
            if (char.IsLetterOrDigit(ch) || ch == '-' || ch == '_')
            {
                cur.Append(ch);
            }
            else
            {
                // '.', whitespace, or any other separator forms a segment boundary.
                if (cur.Length > 0)
                {
                    segments.Add(cur.ToString());
                    cur.Clear();
                }
            }
        }
        if (cur.Length > 0) segments.Add(cur.ToString());

        if (segments.Count == 0)
        {
            error = $"Semantic id '{raw}' contains no usable characters.";
            return false;
        }

        normalized = string.Join('.', segments);
        return true;
    }

    /// <summary>Returns a normalized id, or null when nothing usable remains.</summary>
    public static string? Normalize(string? raw) =>
        TryNormalize(raw, out var norm, out _) ? norm : null;

    /// <summary>
    /// True when <paramref name="id"/> is already canonical (i.e. normalizing it is a
    /// no-op). Rejects empty ids, mixed case, and stray separators.
    /// </summary>
    public static bool IsValid(string? id)
    {
        if (string.IsNullOrWhiteSpace(id)) return false;
        if (!TryNormalize(id, out var norm, out _)) return false;
        return norm == id;
    }

    /// <summary>
    /// Provide a normalized id; throws when the value is unusable, so callers that
    /// require an id get a clear failure instead of silently degrading.
    /// </summary>
    public static string Require(string? raw)
    {
        if (!TryNormalize(raw, out var norm, out var error))
            throw new ArgumentException(error, nameof(raw));
        return norm!;
    }

    /// <summary>
    /// Insert a space at camelCase word boundaries so "CreateInvoice" normalizes to
    /// "create.invoice" rather than "createinvoice". Keeps the segment rule uniform with
    /// the generator. Uppercase runs (acronyms like "PDF") are kept intact.
    /// </summary>
    private static string InsertCamelBoundaries(string name)
    {
        var sb = new StringBuilder();
        for (var i = 0; i < name.Length; i++)
        {
            var c = name[i];
            if (i > 0 && char.IsUpper(c) &&
                (char.IsLower(name[i - 1]) || (i + 1 < name.Length && char.IsLower(name[i + 1]))))
                sb.Append(' ');
            sb.Append(c);
        }
        return sb.ToString();
    }
}
