namespace Telekinesis.Medium;

/// <summary>
/// Declares a member's business intent, e.g. <c>invoice.create</c>. Placed on the command
/// or property that drives an action; consumed by <c>Telekinesis.Medium.Generators</c>.
/// </summary>
[AttributeUsage(AttributeTargets.Property | AttributeTargets.Method | AttributeTargets.Field, AllowMultiple = false)]
public sealed class MediumIntentAttribute(string intent) : Attribute
{
    public string Intent { get; } = intent;
}

/// <summary>Classify a member's action safety; see <see cref="MediumRisk"/>.</summary>
[AttributeUsage(AttributeTargets.Property | AttributeTargets.Method | AttributeTargets.Field, AllowMultiple = false)]
public sealed class MediumRiskAttribute(MediumRisk risk) : Attribute
{
    public MediumRisk Risk { get; } = risk;
}

/// <summary>Mark a member's action as requiring human confirmation before it runs.</summary>
[AttributeUsage(AttributeTargets.Property | AttributeTargets.Method | AttributeTargets.Field, AllowMultiple = false)]
public sealed class MediumRequiresConfirmationAttribute : Attribute;

/// <summary>Override the inferred semantic role (e.g. "button", "textbox", "link").</summary>
[AttributeUsage(AttributeTargets.Property | AttributeTargets.Method | AttributeTargets.Field, AllowMultiple = false)]
public sealed class MediumRoleAttribute(string role) : Attribute
{
    public string Role { get; } = role;
}

/// <summary>Override the autogenerated stable semantic id for a member.</summary>
[AttributeUsage(AttributeTargets.Property | AttributeTargets.Method | AttributeTargets.Field, AllowMultiple = false)]
public sealed class MediumSemanticIdAttribute(string semanticId) : Attribute
{
    public string SemanticId { get; } = semanticId;
}
