<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Telekinesis.Medium</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Telekinesis.Abstractions\Telekinesis.Abstractions.csproj" />
  </ItemGroup>

</Project>
