using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Telekinesis.Medium.Generators;

/// <summary>
/// A build-time Roslyn generator (issue #28, Phase 4) that scans the compilation for
/// members annotated with the Medium marker attributes and emits a strongly-typed
/// <c>GeneratedMedium</c> builder that constructs a <see cref="MediumManifest"/>.
///
/// Everything it infers is deterministic: stable semantic ids come from the member name
/// (via the same rule as <c>MediumSemanticId</c>), roles and actions default to button /
/// invoke, and explicit attributes (<c>[MediumIntent]</c>, <c>[MediumRisk]</c>,
/// <c>[MediumRequiresConfirmation]</c>, <c>[MediumRole]</c>, <c>[MediumSemanticId]</c>)
/// override them. It never requires an LLM or a network service.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class MediumGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor DestructiveNoConfirmation = new(
        id: "MEDIUM001",
        title: "Destructive action without confirmation",
        messageFormat: "Medium: member '{0}' is destructive but does not require confirmation",
        category: "Medium",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var members = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is PropertyDeclarationSyntax or MethodDeclarationSyntax or FieldDeclarationSyntax,
                transform: static (ctx, _) => Analyze(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!)
            .Collect();

        context.RegisterSourceOutput(members, static (spc, all) => Emit(spc, all));
    }

    private static SyntheticMember? Analyze(GeneratorSyntaxContext ctx)
    {
        ISymbol? symbol = ctx.Node switch
        {
            PropertyDeclarationSyntax p => ctx.SemanticModel.GetDeclaredSymbol(p),
            MethodDeclarationSyntax m => ctx.SemanticModel.GetDeclaredSymbol(m),
            FieldDeclarationSyntax f when f.Declaration.Variables.FirstOrDefault() is { } v =>
                ctx.SemanticModel.GetDeclaredSymbol(v),
            _ => null,
        };
        if (symbol is null) return null;

        var attrs = symbol.GetAttributes();
        if (!attrs.Any(IsMediumAttribute)) return null;

        var name = symbol.Name;
        var semanticId = Attr(attrs, "MediumSemanticIdAttribute") ?? Normalize(StripSuffix(name));
        var role = Attr(attrs, "MediumRoleAttribute") ?? "button";
        return new SyntheticMember(
            name, semanticId, role, Attr(attrs, "MediumIntentAttribute"),
            Risk(attrs), Has(attrs, "MediumRequiresConfirmationAttribute"),
            Humanize(StripSuffix(name)), symbol.Locations.FirstOrDefault());
    }

    private static void Emit(SourceProductionContext ctx, ImmutableArray<SyntheticMember> members)
    {
        if (members.IsDefaultOrEmpty) return;
        ctx.CancellationToken.ThrowIfCancellationRequested();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Telekinesis.Medium.Generators — deterministic, no LLM.");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Telekinesis.Medium;");
        sb.AppendLine();
        sb.AppendLine("namespace Telekinesis.Medium.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public static class GeneratedMedium");
        sb.AppendLine("    {");
        sb.AppendLine("        public static MediumManifest Build()");
        sb.AppendLine("        {");
        sb.AppendLine("            return new MediumManifest");
        sb.AppendLine("            {");
        sb.AppendLine("                Application = \"Generated\",");
        sb.AppendLine("                Views = new Dictionary<string, MediumView>");
        sb.AppendLine("                {");
        sb.AppendLine("                    [\"Generated\"] = new MediumView { Elements = new List<MediumElement>");
        sb.AppendLine("                    {");
        foreach (var m in members)
        {
            sb.Append("                        new MediumElement { SemanticId = \"").Append(m.SemanticId).Append('"');
            sb.Append(", Role = \"").Append(m.Role).Append('"');
            sb.Append(", Name = \"").Append(m.AccessibleName).Append('"');
            if (m.Intent is not null) sb.Append(", Intent = \"").Append(m.Intent).Append('"');
            if (m.Risk != "Unknown") sb.Append(", Risk = ").Append(RiskExpr(m.Risk));
            if (m.RequiresConfirmation) sb.Append(", RequiresConfirmation = true");
            sb.Append(", Actions = new List<string> { \"invoke\" } },");
            sb.AppendLine();
        }
        sb.AppendLine("                    } }");
        sb.AppendLine("                }");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource("GeneratedMedium.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));

        // Diagnostics: a destructive action should generally require confirmation.
        foreach (var m in members)
            if (m.Risk == "Destructive" && !m.RequiresConfirmation)
                ctx.ReportDiagnostic(Diagnostic.Create(DestructiveNoConfirmation, m.Location ?? Location.None, m.Name));
    }

    private static string RiskExpr(string risk) => risk switch
    {
        "Read" => "MediumRisk.Read",
        "Write" => "MediumRisk.Write",
        "Destructive" => "MediumRisk.Destructive",
        "Privileged" => "MediumRisk.Privileged",
        _ => "MediumRisk.Unknown",
    };

    private static bool IsMediumAttribute(AttributeData a) =>
        a.AttributeClass is { } c &&
        c.ContainingNamespace.ToDisplayString().StartsWith("Telekinesis.Medium", StringComparison.Ordinal) &&
        c.Name is "MediumIntentAttribute" or "MediumRiskAttribute" or "MediumRequiresConfirmationAttribute"
            or "MediumRoleAttribute" or "MediumSemanticIdAttribute";

    private static string? Attr(ImmutableArray<AttributeData> attrs, string name)
    {
        var a = attrs.FirstOrDefault(x => x.AttributeClass?.Name == name);
        return a is { ConstructorArguments.Length: > 0 } ? a.ConstructorArguments[0].Value as string : null;
    }

    private static bool Has(ImmutableArray<AttributeData> attrs, string name) =>
        attrs.Any(x => x.AttributeClass?.Name == name);

    private static string Risk(ImmutableArray<AttributeData> attrs)
    {
        var a = attrs.FirstOrDefault(x => x.AttributeClass?.Name == "MediumRiskAttribute");
        if (a is null) return "Unknown";
        var v = a.ConstructorArguments.FirstOrDefault().Value;
        var i = (v as int?) ?? -1;
        return i switch { 1 => "Read", 2 => "Write", 3 => "Destructive", 4 => "Privileged", _ => "Unknown" };
    }

    // Strip a verb/command suffix so "CreateInvoiceCommand" -> "CreateInvoice".
    private static string StripSuffix(string name)
    {
        foreach (var suffix in new[] { "Command", "Action", "Button", "Handler" })
            if (name.Length > suffix.Length && name.EndsWith(suffix, StringComparison.Ordinal))
                return name.Substring(0, name.Length - suffix.Length);
        return name;
    }

    // Deterministic semantic-id normalization matching Telekinesis.Medium.MediumSemanticId
    // (including camelCase word splitting).
    private static string Normalize(string raw)
    {
        var s = InsertCamelBoundaries(raw).ToLowerInvariant();
        var segments = new List<string>();
        var cur = new StringBuilder();
        foreach (var ch in s)
        {
            if (char.IsLetterOrDigit(ch) || ch == '-' || ch == '_') cur.Append(ch);
            else if (cur.Length > 0) { segments.Add(cur.ToString()); cur.Clear(); }
        }
        if (cur.Length > 0) segments.Add(cur.ToString());
        return segments.Count > 0 ? string.Join(".", segments) : "unknown";
    }

    private static string InsertCamelBoundaries(string name)
    {
        var sb = new StringBuilder();
        for (var i = 0; i < name.Length; i++)
        {
            var c = name[i];
            if (i > 0 && char.IsUpper(c) &&
                (char.IsLower(name[i - 1]) || (i + 1 < name.Length && char.IsLower(name[i + 1]))))
                sb.Append(' ');
            sb.Append(c);
        }
        return sb.ToString();
    }

    // "CreateInvoice" -> "Create Invoice".
    private static string Humanize(string name)
    {
        var sb = new StringBuilder();
        for (var i = 0; i < name.Length; i++)
        {
            var c = name[i];
            if (i > 0 && char.IsUpper(c) && (char.IsLower(name[i - 1]) ||
                (i + 1 < name.Length && char.IsLower(name[i + 1]))))
                sb.Append(' ');
            sb.Append(c);
        }
        return sb.ToString().Trim();
    }

    private sealed class SyntheticMember
    {
        public SyntheticMember(string name, string semanticId, string role, string? intent, string risk, bool requiresConfirmation, string accessibleName, Location? location)
        {
            Name = name;
            SemanticId = semanticId;
            Role = role;
            Intent = intent;
            Risk = risk;
            RequiresConfirmation = requiresConfirmation;
            AccessibleName = accessibleName;
            Location = location;
        }
        public string Name { get; }
        public string SemanticId { get; }
        public string Role { get; }
        public string? Intent { get; }
        public string Risk { get; }
        public bool RequiresConfirmation { get; }
        public string AccessibleName { get; }
        public Location? Location { get; }
    }
}
